name: blogdeploy

on:
  push:
    branches:
      - master # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "v0.82.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.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 }} #在这里需要特别说明一下， hugo官网的例子用的是github_token，然而实操时才发现github_token不支持外部库，我们采用的两个仓库的方案不能使用github_token。 Github Action除了github_token之外，还支持deploy_token和personal_token。出于方便考虑，我选择了personal_token
          publish_dir: ./public
          publish_branch: master
          # 如果使用自定义域名，还需要添加下面一行配置
          # cname: www.goodfun.me
